language: python
python: "3.6"  # same as SDK base
sudo: required

services:
  - docker

branches:
  only:
    - master
    - dev-testing

env:

before_install:
  - docker version

install:
  - pip install pipenv
  - pipenv install --dev
  - docker pull kbase/kb-sdk
  - cd ..
  - docker run kbase/kb-sdk genscript > kb-sdk
  - export KBSDK=$(pwd)/kb-sdk
  - chmod a+x $KBSDK
  - ls -l
  - echo $KBSDK
  - cd -
  - $KBSDK version

script:
  - $KBSDK validate
  - make test-sdkless
  # TODO make tests for the full stack with local auth, w

after_script:
  - coveralls
